---
# This is the main Ansible playbook
- hosts: localhost
  connection: local
  gather_facts: false
  become: true

  vars:
    ansible_os_family: "Debian"  # Set this to "RedHat" if using a RedHat-based system
    allowed_services:
      - ssh
      - https

  pre_tasks:
    - name: update repositories
      apt:
        update_cache: yes
      changed_when: False

  tasks:
    - import_tasks: tasks/users.yml
    - import_tasks: tasks/packages.yml
    - import_tasks: tasks/firewalld.yml
    - import_tasks: tasks/packages-flatpak.yml
    - import_tasks: tasks/cron.yml

  handlers:
    - name: Restart Fail2Ban
      service:
        name: fail2ban
        state: restarted
