# This is a task file imported by local.yml
- name: install cron job (ansible-pull)
  cron:
    user: ansible
    name: "ansible provision"
    minute: "*/17"
    job: "sudo /usr/bin/ansible-pull -o -i /home/ansible/devops_pull/hosts.ini -U https://github.com/CEP-Comwell/devops_pull.git >> /home/ansible/ansible-pull.log 2>&1"
