- name: Install packages
  apt:
    name:
      - apache2-utils
      - arp-scan
      - attr
      - balena-etcher
      - bridge-utils
      - cpu-checker
      - dnsmasq
      - extlinux
      - f2fs-tools
      - fastboot
      - ffmpeg
      - firefox-esr
      - firewall-config
      - firewalld
      - guestfs-tools
      - guestmount
      - handbrake
      - ibverbs-providers:amd64
      - idle
      - idle-python3.11
      - iperf3
      - ipscan
      - ipset
      - ipxe-qemu
      - ipython3
      - kolourpaint
      - ldmtool
      - mdadm
      - mdevctl
      - mint-meta-codecs
      - mkdocs
      - msr-tools
      - ncat
      - netdiscover
      - netpbm
      - nmap
      - nmap-common
      - node-jquery
      - nodejs
      - notepadqq
      - osinfo-db
      - ovmf
      - pipx
      - printer-driver-cups-pdf
      - python2
      - python2.7
      - python2.7-minimal
      - python2-minimal
      - python3.11-dev
      - python3.11-doc
      - python3.11-examples
      - python3.11-full
      - python3.11-venv
      - python3-all
      - python3-all-dev
      - python3-appdirs
      - python3-asttokens
      - python3-async-timeout
      - python3-attr
      - python3-avahi
      - python3-backcall
      - python3-beniget
      - python3-blinker
      - python3-cap-ng
      - python3-contourpy
      - python3-cycler
      - python3-dateutil
      - python3-decorator
      - python3-dev
      - python3-dill
      - python3-doc
      - python3-examples
      - python3-executing
      - python3-feedparser
      - python3-firewall
      - python3-fonttools
      - python3-fs
      - python3-full
      - python3-gast
      - python3-html2text
      - python3-html5lib
      - python3-importlib-metadata
      - python3-iniconfig
      - python3-ipython
      - python3-jaraco.classes
      - python3-jedi
      - python3-jeepney
      - python3-joblib
      - python3-json-pointer
      - python3-jsonschema
      - python3-jwt
      - python3-keyring
      - python3-kiwisolver
      - python3-launchpadlib
      - python3-lazr.restfulclient
      - python3-lazr.uri
      - python3-libvirt
      - python3-libxml2:amd64
      - python3-livereload
      - python3-lunr
      - python3-lxml:amd64
      - python3-lz4
      - python3-markdown
      - python3-matplotlib
      - python3-matplotlib-inline
      - python3-mergedeep
      - python3-more-itertools
      - python3-mpmath
      - python3-multiprocess
      - python3-nautilus
      - python3-netdisco
      - python3-nftables
      - python3-nltk
      - python3-numpy
      - python3-oauthlib
      - python3-parso
      - python3-pickleshare
      - python3-pil.imagetk:amd64
      - python3-pip
      - python3-pip-whl
      - python3-pluggy
      - python3-ply
      - python3-png
      - python3-prompt-toolkit
      - python3-pure-eval
      - python3-py
      - python3-pyrsistent:amd64
      - python3-pytest
      - python3-pythran
      - python3-pyyaml-env-tag
      - python3-qrcode
      - python3-regex
      - python3-repolib
      - python3-rfc3987
      - python3-scapy
      - python3-scipy
      - python3-secretstorage
      - python3-setuptools
      - python3-setuptools-whl
      - python3-sgmllib3k
      - python3-stack-data
      - python3-sympy
      - python3-tk:amd64
      - python3-tornado
      - python3-tqdm
      - python3-traitlets
      - python3-typing-extensions
      - python3-ufolib2
      - python3-uritemplate
      - python3-userpath
      - python3-venv
      - python3-wadllib
      - python3-watchdog
      - python3-wcwidth
      - python3-webcolors
      - python3-wheel
      - python3-zeroconf
      - python3-zipp
      - python-matplotlib-data
      - s3fs
      - screen
      - scrub
      - seabios
      - shim-unsigned:amd64
      - sleuthkit
      - software-properties-common
      - sonnet-plugins:amd64
      - sphinx-rtd-theme-common
      - spice-client-glib-usb-acl-helper
      - sqlite3
      - ssh
      - tilix
      - tilix-common
    state: present
  register: package_install
  ignore_errors: yes

- name: Check for package installation failures
  debug:
    msg: "Package {{ item.item }} installation failed"
  with_items: "{{ package_install.results }}"
  when: item.failed and 'No package matching' not in item.msg
  failed_when: item.failed and 'No package matching' not in item.msg
