- name: Get the checksum of sudoers_ansible before changes
  stat:
    path: /etc/sudoers.d/sudoers_ansible
  register: sudoers_ansible_before

- name: Apply changes to sudoers_ansible
  copy:
    src: sudoers_ansible
    dest: /etc/sudoers.d/sudoers_ansible

- name: Get the checksum of sudoers_ansible after changes
  stat:
    path: /etc/sudoers.d/sudoers_ansible
  register: sudoers_ansible_after

- name: Verify if sudoers_ansible has changed
  fail:
    msg: "sudoers_ansible has changed"
  when: sudoers_ansible_before.stat.checksum != sudoers_ansible_after.stat.checksum
