# tasks/users.yml

- name: Ensure 'ansible' user exists
  ansible.builtin.user:
    name: ansible
    system: yes
    shell: /bin/bash

- name: Overwrite sudoers file for 'ansible' and validate
  ansible.builtin.shell: |
    echo "ansible ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/ansible
    chmod 0440 /etc/sudoers.d/ansible
    chown root:root /etc/sudoers.d/ansible
    # visudo -cf /etc/sudoers.d/ansible

- name: Report that sudoers file was overwritten
  ansible.builtin.debug:
    msg: "sudoers_ansible file was overwritten"
