# tasks/users.yml

- name: Check if 'ansible' user exists
  command: getent passwd ansible
  register: ansible_user_check
  failed_when: false
  changed_when: false

- name: Create 'ansible' user if it does not exist
  ansible.builtin.user:
    name: ansible
    system: yes
    shell: /bin/bash
  when: ansible_user_check.rc != 0

- name: Check if sudoers file for 'ansible' exists
  ansible.builtin.stat:
    path: /etc/sudoers.d/ansible
  register: sudoers_file_before

- name: Copy sudoers file for 'ansible'
  ansible.builtin.copy:
    src: files/sudoers_ansible
    dest: /etc/sudoers.d/ansible
    owner: root
    group: root
    mode: '0440'
  notify: Validate sudoers file

- name: Check if sudoers file for 'ansible' changed
  ansible.builtin.stat:
    path: /etc/sudoers.d/ansible
  register: sudoers_file_after

- name: Report if sudoers file has changed
  ansible.builtin.debug:
    msg: "sudoers_ansible file has changed"
  when: sudoers_file_before.stat.checksum != sudoers_file_after.stat.checksum
