# tasks/users.yml

- name: Check if 'ansible' user exists
  command: getent passwd ansible
  register: ansible_user_check
  failed_when: false
  changed_when: false

- name: Create 'ansible' user if it does not exist
  ansible.builtin.user:
    name: ansible
    system: yes
    shell: /bin/bash
  when: ansible_user_check.rc != 0

- name: Ensure sudoers file for 'ansible' is present
  ansible.builtin.copy:
    src: files/sudoers_ansible
    dest: /etc/sudoers.d/ansible
    owner: root
    group: root
    mode: '0440'
  notify: Validate sudoers file
  register: copy_result

- name: Report if sudoers file has changed
  ansible.builtin.debug:
    msg: "sudoers_ansible file has changed"
  when: copy_result.changed
