# tasks/users.yml

- name: Ensure 'ansible' user exists
  ansible.builtin.user:
    name: ansible
    system: yes
    shell: /bin/bash

- name: Overwrite sudoers file for 'ansible'
  ansible.builtin.copy:
    src: files/sudoers_ansible
    dest: /etc/sudoers.d/ansible
    owner: root
    group: root
    mode: '0440'
    force: yes
  notify: Validate sudoers file

- name: Ensure correct permissions for sudoers file
  ansible.builtin.file:
    path: /etc/sudoers.d/ansible
    owner: root
    group: root
    mode: '0440'

- name: Report that sudoers file was overwritten
  ansible.builtin.debug:
    msg: "sudoers_ansible file was overwritten"
