# tasks/users.yml
# This is a task file imported by local.yml
# It manages user accounts and sudoers configuration

- name: Write sudoers file for 'ansible'
  ansible.builtin.copy:
    content: "ansible ALL=(ALL) NOPASSWD:ALL"
    dest: /etc/sudoers.d/ansible
    owner: root
    group: root
    mode: '0440'

- name: Set permissions for sudoers file
  ansible.builtin.file:
    path: /etc/sudoers.d/ansible
    owner: root
    group: root
    mode: '0440'