---
- name: Ensure the keyring directory exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Microsoft GPG key (ASCII)
  ansible.builtin.get_url:
    url: https://packages.microsoft.com/keys/microsoft.asc
    dest: /etc/apt/keyrings/microsoft.asc
    mode: '0644'

- name: Convert Microsoft GPG key to binary format
  ansible.builtin.command:
    cmd: gpg --dearmor -o /etc/apt/keyrings/microsoft.gpg /etc/apt/keyrings/microsoft.asc
  args:
    creates: /etc/apt/keyrings/microsoft.gpg

- name: Set permissions on the binary GPG key
  ansible.builtin.file:
    path: /etc/apt/keyrings/microsoft.gpg
    mode: '0644'

- name: Add Visual Studio Code repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/microsoft.gpg] https://packages.microsoft.com/repos/code stable main"
    state: present
    update_cache: yes

<<<<<<< HEAD
# Ensure the apt cache is updated
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

# Install Visual Studio Code
=======
>>>>>>> refs/remotes/origin/main
- name: Install Visual Studio Code
  ansible.builtin.apt:
    name: code
    state: present
